### PR TITLE
Added an option to wrap full objects into observable

### PR DESCRIPTION
**Pull request by bago**
By passing "true" as the third parameter to the wrap method, you have
nested objects wrapped in observable too.

### CODE REVIEW

**Comment by arj03** [comment]
Looks good. Thanks for the patch. Not sure why anyone would polute they objects with functions ;)

**Comment by arj03** [comment]
Could you provide an example where this makes sense? Also tests needs to be updated.

**Comment by bago** [comment]
I use knockout-wrap in an SPA product I'm opensourcing: https://github.com/voidlabs/mosaico
It uses a big nested model to represent an email template. Each "block" or "element" in the template is represented by an object, when you drop an image in the template you simply replace an existing object with another, so, using observables everything works fine because you observe full objects and not only leafs.

About tests, I'll try to provide some tests later.. now I'm full on the opensourcing of Mosaico.

**Comment by bago** [comment]
Let me know If you think that wrapping objects does not belong to this library so I simply put the customized library in my sources instead of depending on this one at build time via bower.

**Comment by arj03** [comment]
Just an example first were you use it would be nice

**Comment by bago** [comment]
I explained my use case 3 comments above, if you want to see the code I'll comment here once I will have pushed my first opensource release for mosaico.

**Comment by bago** [comment]
Hi, I just pushed mosaico, our opensource email template editor using knockout-wrap "patched" to wrap full objects. When you drag/drop images in the template your are replacing full observable objects with new ones. Also, loading a new template will work by replacing the full "content" tree of observables.

Here is the library:
https://github.com/voidlabs/mosaico
And here a Live demo:
http://mosaico.io

Mosaico currently depend on my custom knockout-wrap fork on github. but I don't like depending on forked repositories. So if you think this feature doesn't belong to the wrapper I can understand this and I will simply put the custom wrapper in mosaico sources removing the dependency from knockout.wrap.

Thank you,
Stefano

**Comment by arj03** [comment]
Okay, please update the diff with tests, then I'll merge

**Comment by bago** [comment]
Just for reference, this has been "merged" but then "reverted" in https://github.com/arj03/knockout.wrap/pull/10

Unfortunately I didn't get any notification about the "revert" so I don't know what was the problem.

Do you expect something more in the code? Or did you decide that this kind of behaviour doesn't belong to the library?

Please tell me, so I can move forward by providing updated code or by simply copying the changed code to my library so I can adapt it to my needs.

**Comment by arj03** [comment]
Yeah sorry about the mess. Reverted because of missing tests.

**Pull request merged**
